"""
Django settings for quatromaos project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
PROJECT_ROOT_PATH=os.path.dirname(os.path.abspath(__file__))

DEBUG = True
myhost = os.uname()[1]

if myhost == 'ghabriel-pc':
    ONLINE = False
    # site = 'https://localhost:8000/'
    # LOGOUT_REDIRECT_URL = site + 'accounts/login/'
    # LOGIN_REDIRECT_URL = site
    # LOGIN_URL = LOGOUT_REDIRECT_URL

elif myhost == 'MacBook-Pro.local':
    ONLINE = False
    # site = 'http://localhost:8000/'
    # LOGOUT_REDIRECT_URL = site + 'accounts/login/'
    # LOGIN_REDIRECT_URL = site
    # LOGIN_URL = LOGOUT_REDIRECT_URL

elif myhost == 'venancio':
    ONLINE = False
    site = 'http://localhost:8000/'
    LOGOUT_REDIRECT_URL = site + 'accounts/login/'
    LOGIN_REDIRECT_URL = site
    LOGIN_URL = LOGOUT_REDIRECT_URL

elif myhost == 'leandro-pc':
    ONLINE = False
    # site = 'http://localhost:8000/'
    # LOGOUT_REDIRECT_URL = site + 'accounts/login/'
    # LOGIN_REDIRECT_URL = site
    # LOGIN_URL = LOGOUT_REDIRECT_URL

elif myhost == 'MacBook-Pro-de-Ana-630.local':
    ONLINE = False
    site = 'http://localhost:8000/'
    LOGOUT_REDIRECT_URL = site + 'accounts/login/'
    LOGIN_REDIRECT_URL = site
    LOGIN_URL = LOGOUT_REDIRECT_URL

elif myhost =='web7641.kinghost.net':
    ONLINE = True
    site = 'https://4maos.com.br/quatromaos/'
    LOGOUT_REDIRECT_URL = site+'accounts/login/'
    LOGIN_REDIRECT_URL =  site
    LOGIN_URL = LOGOUT_REDIRECT_URL

else:
    ONLINE = True
    site = 'https://devpublicon.kinghost.net/quatromaos/'
    LOGOUT_REDIRECT_URL = site
    # DEBUG = False

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qt3etpekg5()(3_dau97)t*5x*at))tarecs%xj+34j3nnypj_'

ALLOWED_HOSTS = [
'devpublicon.kinghost.net',
'www.devpublicon.kinghost.net',
'localhost',
'www.4maos.com.br',
'4maos.com.br',
'127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'adm',
    'cliente',
    'bootstrap3',
    'django_filters',
    'django_cron',
    # 'import_export',
]

CRON_CLASSES = [
    "utilitarios.utilitarios.CronJob",
    # ...
]
# SMTP Host	Para Hospedagens: smtp.kinghost.net | Para revendas: smtp.uni5.net
# SMTP Port	587
# Encryption	No Encryption
# Authentication	Yes: Use SMTP authentication
# Username	Conta de email completa (Exemplo: contato@site.com.br)
# Password	Senha da conta de email
if ONLINE:
    EMAIL_HOST = 'smtp.kinghost.net'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = 'sistema@4maos.com.br'
    EMAIL_HOST_PASSWORD = 's1st3maquatromaos'
    EMAIL_USE_TLS = True
    IMPORT_EXPORT_USE_TRANSACTIONS = True
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        ...
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quatromaos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "utilitarios.utilitarios.utilitarios",
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'quatromaos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
if ONLINE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'devpublicon37',
            'USER': 'devpublicon37',
            'PASSWORD': '4maosdjango',
            'HOST': 'mysql.devpublicon.kinghost.net',
            'PORT': '',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'quatromaos',
            'USER': 'root',
            'PASSWORD': 'root',
            'HOST': '127.0.0.1',
            'PORT': '',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')#.replace('\\', '/')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

if ONLINE:
    MEDIA_URL = site+'static/uploads/'
    MEDIA_ROOT = '/home/4maos/www/static/uploads/'
    STATIC_ROOT = '/home/4maos/www/static/'

    # STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"),]
