# Generated by Django 2.1.4 on 2019-02-16 19:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Inativo', 'Inativo'), ('Ativo', 'Ativo')], default='Inativo', max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('cpf', models.CharField(max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('cargo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento')),
                ('rg', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='RG')),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='CNPJ')),
                ('razaoSocial', models.CharField(blank=True, max_length=500, null=True, verbose_name='Razao social')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero')),
                ('bairro', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=300, null=True, verbose_name='Cidade')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cartaoCredito', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cartao de crédito')),
                ('nomeTitular', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome do titular')),
                ('dataValidade', models.DateField(blank=True, null=True, verbose_name='Data da validade')),
                ('cvv', models.CharField(blank=True, max_length=5, null=True, verbose_name='CVV')),
                ('dataDeCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Plano')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControleDeCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDeCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('inicioDeVigenciaDoPlano', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('terminoDeVigenciaDoPlano', models.DateTimeField(blank=True, null=True)),
                ('inicioDeVigenciaMensal', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('terminoDeVigenciaMensal', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 19, 12, 31, 196913, tzinfo=utc), null=True)),
                ('numeroDeVisualizacoesPagas', models.PositiveIntegerField(blank=True, null=True)),
                ('numeroDeVisualizacoesDisfarcadas', models.PositiveIntegerField(blank=True, null=True)),
                ('numeroDeServicosSolicitados', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('oportunidadesDisfarcadasVisualizadasMensais', models.ManyToManyField(blank=True, help_text='Oportunidades disfarçadas visualizadas mensalmente.', related_name='log_oportunidadesdisfarcadas', to='adm.Oportunidade', verbose_name='Disfarçadas')),
                ('oportunidadesPagasVisualizadasMensais', models.ManyToManyField(blank=True, help_text='Oportunidades pagas visualizadas mensalmente.', related_name='log_oportunidadespagas', to='adm.Oportunidade', verbose_name='Pagas')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Plano')),
                ('servicosSolicitadosMensalmente', models.ManyToManyField(blank=True, help_text='Serviços solicitados mensalmente.', related_name='log_servicos', to='adm.Servico', verbose_name='Serviços')),
            ],
        ),
        migrations.CreateModel(
            name='NegociacoesDeOportunidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aguardando posicionamento', 'Aguardando posicionamento'), ('Acordo feito', 'Acordo feito'), ('Encerrada', 'Encerrada')], max_length=30)),
                ('dataDeCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('controleDeCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ControleDeCliente')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Oportunidade')),
            ],
        ),
    ]
