# Generated by Django 2.1.4 on 2019-02-16 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20190216_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 16, 20, 49, 22, 85777, tzinfo=utc), null=True),
        ),
    ]
