# Generated by Django 2.1.4 on 2019-02-17 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20190217_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 19, 30, 17, 317655, tzinfo=utc), null=True),
        ),
    ]
