# Generated by Django 2.1.4 on 2019-02-17 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20190217_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 19, 31, 18, 643671, tzinfo=utc), null=True),
        ),
    ]
