# Generated by Django 2.1.4 on 2019-02-18 00:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0007_auto_20190217_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('dataDeCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpfDoResponsavel',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF do contador responsável pela empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='crcDoResponsavel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='CRC do contador responsável pela empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nomeDoResponsavel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome do contador responsável pela empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoDeEscritorio',
            field=models.CharField(blank=True, choices=[('Empresa', 'Empresa'), ('Autônomo', 'Autônomo')], default='Empresa', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 18, 0, 12, 52, 378259, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='areaDeAtuacao',
            field=models.ManyToManyField(blank=True, help_text='Selecione as áreas de atuação de sua empresa', related_name='cliente_areadeatuacao', to='cliente.AreaDeAtuacao', verbose_name='Área de atuação'),
        ),
    ]
