# Generated by Django 2.1.4 on 2019-03-05 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_auto_20190217_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areadeatuacao',
            options={'verbose_name': 'Área de atuação', 'verbose_name_plural': 'Áreas de atuação'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='senhaTemporaria',
            field=models.CharField(max_length=255, null=True, verbose_name='Senha temporária'),
        ),
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 5, 15, 55, 25, 959381, tzinfo=utc), null=True),
        ),
    ]
