# Generated by Django 2.1.4 on 2019-03-08 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_auto_20190305_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 8, 17, 36, 14, 383274, tzinfo=utc), null=True),
        ),
    ]
