# Generated by Django 2.1.4 on 2019-03-25 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_auto_20190308_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razaoSocial',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Razão Social / Empresa'),
        ),
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 25, 21, 37, 6, 105354, tzinfo=utc), null=True),
        ),
    ]
