# Generated by Django 2.1.4 on 2019-03-25 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_auto_20190325_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 25, 21, 57, 2, 601947, tzinfo=utc), null=True),
        ),
    ]
