# Generated by Django 2.1 on 2019-03-28 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_auto_20190325_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 28, 1, 3, 9, 115965, tzinfo=utc), null=True),
        ),
    ]
