# Generated by Django 2.1.4 on 2019-03-31 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_auto_20190327_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 30, 19, 9, 43, 957384, tzinfo=utc), null=True),
        ),
    ]
