# Generated by Django 2.1.4 on 2019-04-14 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_auto_20190331_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 18, 43, 33, 573368, tzinfo=utc), null=True),
        ),
    ]
