# Generated by Django 2.2.1 on 2019-05-02 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_auto_20190414_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledecliente',
            name='terminoDeVigenciaMensal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 2, 21, 4, 51, 993668, tzinfo=utc), null=True),
        ),
    ]
