# Generated by Django 2.1.4 on 2019-02-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('dataDeCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoDeTemplate',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adm.TipoDeTemplate', verbose_name='Forma de exibição na página'),
            preserve_default=False,
        ),
    ]
