# Generated by Django 2.1.4 on 2019-02-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20190216_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodetemplate',
            name='autor',
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipoDeTemplate',
            field=models.CharField(choices=[('site', 'site'), ('lista comum', 'lista comum'), ('lista compravel', 'lista compravel')], max_length=30, verbose_name='Forma de exibição do serviço'),
        ),
        migrations.DeleteModel(
            name='TipoDeTemplate',
        ),
    ]
