# Generated by Django 2.1.4 on 2019-03-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_auto_20190217_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.RemoveField(
            model_name='plano',
            name='quantidadePadraoDeOportunidadesDisfarcadas',
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Cidade'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='grauDeUrgencia',
            field=models.CharField(blank=True, choices=[('Imediata', 'Imediata'), ('Em breve', 'Em breve'), ('Apenas uma pesquisa', 'Apenas uma pesquisa')], max_length=300, null=True, verbose_name='Grau de Urgência'),
        ),
    ]
