# Generated by Django 2.1.4 on 2019-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_auto_20190305_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeServicosDoFiltroDeOportunidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicosFiltraveis', models.ManyToManyField(blank=True, help_text='Por favor, selecione os serviços que farão parte do filtro de oportunidades.', null=True, related_name='lista_servico', to='adm.Servico', verbose_name='Serviços Filtráveis')),
            ],
            options={
                'verbose_name': 'Lista de serviços do filtro de oportunidades',
                'verbose_name_plural': 'Lista de serviços',
            },
        ),
        migrations.AlterField(
            model_name='linksdomenu',
            name='link',
            field=models.CharField(choices=[('oportunidades', 'oportunidades'), ('oportunidades-disfarcadas', 'oportunidades-disfarcadas'), ('duvidas-frequentes', 'duvidas-frequentes'), ('conteudo-educativo', 'conteudo-educativo'), ('material-marketing-apoio', 'material-marketing-apoio'), ('material-marketing-avancado', 'material-marketing-avancado'), ('perfil', 'perfil')], max_length=500),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='numeroDeParticipantes',
            field=models.IntegerField(null=True, verbose_name='Número de participantes'),
        ),
    ]
