# Generated by Django 2.1.4 on 2019-03-25 21:37

import adm.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_auto_20190308_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=96, null=True, unique=True, verbose_name='Nome')),
                ('link', models.SlugField(help_text="URLs devem ser compostos apenas de letras minusculas, '_' , '-' e numeros.", null=True, unique=True, verbose_name='URL amigavel')),
                ('sinopse', models.CharField(blank=True, max_length=152, null=True, verbose_name='Sinopse')),
                ('conteudo', models.TextField(blank=True, default='', null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to=adm.models.get_image_galeria_path, verbose_name='Capa')),
                ('dataDeCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='LivrosArtigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=96, null=True, unique=True, verbose_name='Nome')),
                ('autor', models.CharField(blank=True, max_length=152, null=True, verbose_name='Autor')),
                ('sinopse', models.CharField(blank=True, max_length=152, null=True, verbose_name='Sinopse')),
                ('capa', models.ImageField(blank=True, null=True, upload_to=adm.models.get_image_galeria_path, verbose_name='Capa')),
                ('dataDeCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Arquivo')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True, unique=True, verbose_name='Nome')),
                ('urlYoutube', models.CharField(blank=True, help_text='Insira a URL do video.', max_length=150, null=True, verbose_name='Url do video')),
                ('assunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto')),
                ('dataDeCadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='quantidadeDeFuncionarios',
        ),
        migrations.AlterField(
            model_name='linksdomenu',
            name='link',
            field=models.CharField(choices=[('oportunidades', 'oportunidades'), ('oportunidades-disfarcadas', 'oportunidades-disfarcadas'), ('duvidas-frequentes', 'duvidas-frequentes'), ('conteudo-educativo', 'conteudo-educativo'), ('material-marketing-apoio', 'material-marketing-apoio'), ('material-marketing-avancado', 'material-marketing-avancado'), ('perfil', 'perfil'), ('planos', 'planos')], max_length=500),
        ),
        migrations.AlterField(
            model_name='listadeservicosdofiltrodeoportunidades',
            name='servicosFiltraveis',
            field=models.ManyToManyField(blank=True, help_text='Por favor, selecione os serviços que farão parte do filtro de oportunidades.', related_name='lista_servico', to='adm.Servico', verbose_name='Serviços Filtráveis'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='numeroDeParticipantes',
            field=models.PositiveIntegerField(null=True, verbose_name='Número de participantes'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='preferencia',
            field=models.CharField(blank=True, choices=[('Melhor qualidade', 'Melhor qualidade'), ('Menor preço', 'Menor preço'), ('Custo / Benefícios', 'Custo / Benefícios')], max_length=300, null=True, verbose_name='Preferência'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='tipoDeEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.TipoDeEmpresa', verbose_name='Tipo de Empresa'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='diasParaExpirar',
            field=models.PositiveIntegerField(null=True, verbose_name='Dias para expirar'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='mesesParaExpirar',
            field=models.PositiveIntegerField(null=True, verbose_name='Numero de meses de vigência'),
        ),
    ]
