# Generated by Django 2.1.4 on 2019-03-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_auto_20190325_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudoeducativo',
            name='galeria',
        ),
        migrations.AddField(
            model_name='conteudoeducativo',
            name='blog',
            field=models.ManyToManyField(blank=True, related_name='conteudoeducativo_blog', to='adm.Blog', verbose_name='Vídeos'),
        ),
        migrations.AddField(
            model_name='conteudoeducativo',
            name='livros',
            field=models.ManyToManyField(blank=True, related_name='conteudoeducativo_livros', to='adm.LivrosArtigos', verbose_name='Ebooks'),
        ),
        migrations.AddField(
            model_name='conteudoeducativo',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='conteudoeducativo_videos', to='adm.Videos', verbose_name='Vídeos'),
        ),
        migrations.AlterField(
            model_name='conteudoeducativo',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
