# Generated by Django 2.1 on 2019-03-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_auto_20190325_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='valorCentavos',
        ),
        migrations.AddField(
            model_name='servico',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conteudoeducativo',
            name='blog',
            field=models.ManyToManyField(blank=True, related_name='conteudoeducativo_blog', to='adm.Blog', verbose_name='Blog'),
        ),
    ]
