# Generated by Django 2.1.4 on 2019-04-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_auto_20190331_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipoDeTemplate',
        ),
        migrations.AddField(
            model_name='blog',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Arquivo'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='urlYoutube',
            field=models.CharField(blank=True, help_text='Insira a URL de incorporação do video. Não esqueça do http://. Exemplo: http://www.youtube.com/embed/C_NPf7dWP7g', max_length=150, null=True, verbose_name='Url do video'),
        ),
    ]
