# Generated by Django 2.1.4 on 2019-07-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_auto_20190414_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='visualizar',
            field=models.BooleanField(default=False, help_text='Este serviço deve ter o botão de visualizar?'),
        ),
    ]
